local comments = require("herdr-nvim.comments")

local function scratch(lines, name)
  local b = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(b, 0, -1, false, lines)
  if name then vim.api.nvim_buf_set_name(b, name) end
  return b
end

T.test("comments: add + get returns live data", function()
  comments.clear()
  local b = scratch({ "l1", "l2", "l3", "l4" }, "/tmp/hn-a.lua")
  local id = comments.add(b, { start_line = 2, end_line = 3 }, "fix this")
  local c = comments.get(id)
  T.eq({ c.start_line, c.end_line, c.text }, { 2, 3, "fix this" })
  T.ok(c.file:match("hn%-a%.lua$"))
end)

T.test("comments: range tracks edits above it", function()
  comments.clear()
  local b = scratch({ "l1", "l2", "l3", "l4" })
  local id = comments.add(b, { start_line = 3, end_line = 4 }, "x")
  vim.api.nvim_buf_set_lines(b, 0, 0, false, { "new0", "new1" }) -- insert 2 lines at top
  local c = comments.get(id)
  T.eq({ c.start_line, c.end_line }, { 5, 6 })
end)

T.test("comments: snippet returns current covered lines", function()
  comments.clear()
  local b = scratch({ "a", "b", "c" })
  local id = comments.add(b, { start_line = 2, end_line = 3 }, "x")
  vim.api.nvim_buf_set_lines(b, 1, 2, false, { "B-EDITED" })
  T.eq(comments.snippet(id), { "B-EDITED", "c" })
end)

T.test("comments: exclusive endpoint excludes following line after final-line expansion", function()
  comments.clear()
  local b = scratch({ "l1", "l2", "l3", "l4" })
  local id = comments.add(b, { start_line = 2, end_line = 3 }, "x")
  vim.api.nvim_buf_set_lines(b, 2, 3, false, { "l3a", "l3b" })
  T.eq(comments.snippet(id), { "l2", "l3a", "l3b" })
end)

T.test("comments: edit, delete, list ordering", function()
  comments.clear()
  local b1 = scratch({ "x" }, "/tmp/hn-b.lua")
  local b2 = scratch({ "x", "y" }, "/tmp/hn-a2.lua")
  local i1 = comments.add(b1, { start_line = 1, end_line = 1 }, "one")
  local i2 = comments.add(b2, { start_line = 2, end_line = 2 }, "two")
  local i3 = comments.add(b2, { start_line = 1, end_line = 1 }, "three")
  T.ok(comments.edit(i1, "one-edited"))
  T.eq(comments.get(i1).text, "one-edited")
  -- sorted by file then start_line: hn-a2:1, hn-a2:2, hn-b:1
  local l = comments.list()
  T.eq({ l[1].id, l[2].id, l[3].id }, { i3, i2, i1 })
  T.ok(comments.delete(i2))
  T.eq(#comments.list(), 2)
  T.eq(comments.get(i2), nil)
end)

T.test("comments: list drops wiped buffers", function()
  comments.clear()
  local b = scratch({ "x" })
  comments.add(b, { start_line = 1, end_line = 1 }, "gone")
  vim.api.nvim_buf_delete(b, { force = true })
  T.eq(comments.list(), {})
end)

T.test("comments: sub-line span snippet is the exact selected text", function()
  comments.clear()
  local b = scratch({ "the quick brown fox" })
  local id = comments.add(b, { start_line = 1, end_line = 1, cols = { 4, 9 } }, "x") -- "quick"
  T.eq(comments.snippet(id), { "quick" })
  local c = comments.get(id)
  T.eq({ c.start_line, c.end_line, c.cols[1], c.cols[2] }, { 1, 1, 4, 9 })
end)

T.test("comments: sub-line span tracks edits above it", function()
  comments.clear()
  local b = scratch({ "the quick brown fox" })
  local id = comments.add(b, { start_line = 1, end_line = 1, cols = { 4, 9 } }, "x")
  vim.api.nvim_buf_set_lines(b, 0, 0, false, { "inserted" })
  local c = comments.get(id)
  T.eq({ c.start_line, c.cols[1], c.cols[2] }, { 2, 4, 9 })
  T.eq(comments.snippet(id), { "quick" })
end)

T.test("comments: sub-line span does not absorb insertions at either boundary", function()
  comments.clear()
  local b = scratch({ "the quick brown fox" })
  local id = comments.add(b, { start_line = 1, end_line = 1, cols = { 4, 9 } }, "x")
  vim.api.nvim_buf_set_text(b, 0, 4, 0, 4, { "very " })
  vim.api.nvim_buf_set_text(b, 0, 14, 0, 14, { "ly" })
  T.eq(vim.api.nvim_buf_get_lines(b, 0, -1, false), { "the very quickly brown fox" })
  T.eq(comments.snippet(id), { "quick" })
end)

T.test("comments: deleting a sub-line span leaves an empty snippet", function()
  comments.clear()
  local b = scratch({ "the quick brown fox" })
  local id = comments.add(b, { start_line = 1, end_line = 1, cols = { 4, 9 } }, "x")
  vim.api.nvim_buf_set_text(b, 0, 4, 0, 10, {}) -- delete "quick "
  T.eq(comments.snippet(id), { "" })
  T.eq(vim.api.nvim_buf_get_lines(b, 0, -1, false), { "the brown fox" })
end)

T.test("comments: multi-line span snippet includes partial first/last line", function()
  comments.clear()
  local b = scratch({ "alpha beta", "gamma delta" })
  local id = comments.add(b, { start_line = 1, end_line = 2, cols = { 6, 5 } }, "x") -- "beta" .. "\n" .. "gamma"
  T.eq(comments.snippet(id), { "beta", "gamma" })
end)

T.test("comments: whole-line comment has no columns", function()
  comments.clear()
  local b = scratch({ "a", "b", "c" })
  local id = comments.add(b, { start_line = 2, end_line = 3 }, "x")
  local c = comments.get(id)
  T.eq(c.cols, nil)
  T.eq(comments.snippet(id), { "b", "c" })
end)
